//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EX_30122020_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public long id { get; set; }
        public string name { get; set; }
        public long disctrict_id { get; set; }
        public string mayor { get; set; }
        public Nullable<int> population { get; set; }
    }
}
